/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
    @Test void authorPresent() throws FileNotFoundException {
//        String author = "George Orwell";
//        String text = "His answer to every problem, every setback was “I will work harder!” —which he had adopted as his personal motto.";
//        System.out.println(author + "1");

        App.authorQuote(5);
        assertTrue(App.authorQuote(5).equals("The author, George Orwell, once said, \"His answer to every problem, every setback was “I will work harder!” —which he had adopted as his personal motto.\""));
    }
}
